version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      
echo "Installing dependencies..."
pip install -r requirement.txt -t lib
build:
  commands:
echo "Zipping deployment package..."
cd lib
zip -r9 ../deployment_packages.zip .
cd ..
zip -g deployment_packages.zip lambda_cicd.py
post_build:
  commands:
echo "Uploading to S3..."
aws s3 cp deployment_packages.zip s3://s3-buildcode/ 
aws lambda update-function-code --function-name Doordash-cicd-lambda --s3-bucket s3-buildcode --s3-key deployment_packages.zip
echo "Deployment complete!"